### ISSUE TITLE
Error to launch

### ISSUE THREAD

**Issue by dzpt** [cxa/AppExtensionCommunicator#1]
I've downloaded and run example project and get this error:
`/Users/*/Downloads/AppExtensionCommunicator-master/Example/TodayWidget/TodayViewController.swift:10:8: No such module 'AppExtensionCommunicator'`

**Comment by cxa** [comment]
Sorry I can't reproduce this issue. Make sure don't open AppExtensionCommunicator.xcodeproj in Xcode on the same time while Example.xcodeproj opening.

**Comment by dzpt** [comment]
I've tried it again. And it works.
Many tks, i use it for my custom keyboard. But does it impact to the performance?

I see the method `observeMessageForIdentifier` , does it run in the background everytime to listen message from containing app?

**Comment by cxa** [comment]
Should have no significant impact, it does use the method from CoreFoundation. Sure it run when app is not been killed.
